name: ffxiv-rss-actions
on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  ffxiv-rss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser requests beautifulsoup4

      - name: Fetch and send RSS News
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          RSS_URL: https://jp.finalfantasyxiv.com/lodestone/news/news.xml
          STATE_FILE: news_state.json
        run: |
          python rss_parser.py "$RSS_URL" "$STATE_FILE"

      - name: Fetch and send RSS Topics
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          RSS_URL: https://jp.finalfantasyxiv.com/lodestone/news/topics.xml
          STATE_FILE: topics_state.json
        run: |
          python rss_parser.py "$RSS_URL" "$STATE_FILE"

      - name: Fetch and send RSS Blog
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          RSS_URL: https://jp.finalfantasyxiv.com/blog/atom.xml
          STATE_FILE: atom_state.json
        run: |
          python rss_parser.py "$RSS_URL" "$STATE_FILE"

      - name: Check for changes
        id: check_changes
        run: |
          git add news_state.json topics_state.json
          if git diff-index --quiet HEAD --; then
            echo "No changes detected"
            echo "no_changes=true" >> $GITHUB_ENV
          else
            echo "Changes detected"
            echo "no_changes=false" >> $GITHUB_ENV
          fi

      - name: Commit and push changes
        if: env.no_changes == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "action@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git commit -m "Update state files"
          git push
