name: ffxiv-rss-actions
on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:
jobs:
  ffxiv-rss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser requests beautifulsoup4

      - name: Fetch and send RSS News
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          RSS_URL: https://jp.finalfantasyxiv.com/lodestone/news/news.xml
          STATE_FILE: news_state.json
        run: |
          python rss_parser.py "$RSS_URL" "$STATE_FILE"

      - name: Fetch and send RSS Topics
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          RSS_URL: https://jp.finalfantasyxiv.com/lodestone/news/topics.xml
          STATE_FILE: topics_state.json
        run: |
          python rss_parser.py "$RSS_URL" "$STATE_FILE"
